"""Concatenation of AAC audio for the audiobook, checked by decoding the result.

Two defects reported success while producing wrong audio:

- pauses were generated by pydub at its 11025 Hz default and stream-copied into
  a 24 kHz track, so a 3 s pause played as about 1.4 s and chapter markers
  drifted late;
- a path containing an apostrophe ended the concat list early, and ffmpeg
  exited 0 having written only the entries before it.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

from audiobook.concat import ConcatError, concat_audio, decoded_duration, write_silence

pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg not installed",
)


def tone(path: Path, seconds: float, rate: int = 24000, channels: int = 1) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-f", "lavfi",
            "-i", f"sine=frequency=440:sample_rate={rate}:duration={seconds}",
            "-ac", str(channels), "-c:a", "aac", "-movie_timescale", "24000", "-y", str(path),
        ],
        check=True,
    )
    return path


def test_a_pause_lasts_as_long_as_asked(tmp_path: Path) -> None:
    first = tone(tmp_path / "a.m4a", 1.0)
    second = tone(tmp_path / "b.m4a", 1.0)
    pause = write_silence(tmp_path / "pause.m4a", 3.0, like=first)
    out = concat_audio([first, pause, second], tmp_path / "out.m4a")
    assert decoded_duration(out) == pytest.approx(5.0, abs=0.1)


def test_silence_matches_the_speech_format(tmp_path: Path) -> None:
    speech = tone(tmp_path / "speech.m4a", 1.0, rate=22050, channels=1)
    pause = write_silence(tmp_path / "pause.m4a", 1.0, like=speech)
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-select_streams", "a:0",
         "-show_entries", "stream=sample_rate,channels", "-of", "csv=p=0", str(pause)],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    assert probe == "22050,1"


def test_an_apostrophe_in_the_path_keeps_every_input(tmp_path: Path) -> None:
    work = tmp_path / "it's a book"
    parts = [tone(work / f"part {i}'s.m4a", 1.0) for i in range(3)]
    out = concat_audio(parts, work / "out.m4a")
    assert decoded_duration(out) == pytest.approx(3.0, abs=0.1)


def test_inputs_in_different_formats_are_refused(tmp_path: Path) -> None:
    a = tone(tmp_path / "a.m4a", 1.0, rate=24000)
    b = tone(tmp_path / "b.m4a", 1.0, rate=11025)
    with pytest.raises(ConcatError, match="sample rate"):
        concat_audio([a, b], tmp_path / "out.m4a")


def test_a_short_output_is_refused(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """If ffmpeg drops inputs and still exits 0, the result must not pass."""
    from audiobook import concat

    parts = [tone(tmp_path / f"{i}.m4a", 1.0) for i in range(3)]
    real_list = concat._concat_list
    # Simulate the old truncation: the list ffmpeg reads holds only the first input.
    monkeypatch.setattr(concat, "_concat_list", lambda paths: real_list(paths[:1]))
    with pytest.raises(ConcatError, match="expected about 3.0"):
        concat_audio(parts, tmp_path / "out.m4a")


def test_ffmpeg_failure_carries_its_stderr(tmp_path: Path) -> None:
    broken = tmp_path / "broken.m4a"
    broken.write_bytes(b"not audio")
    with pytest.raises(ConcatError) as excinfo:
        concat_audio([broken], tmp_path / "out.m4a")
    assert "broken.m4a" in str(excinfo.value)
